sudo:  required

services:
  - docker

before_install:
  - docker build -t kalin-the-builder/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kalin-the-builder/react-test npm test

afterafter_success:
  - docker build -t kalin-the-builder/multi-client ./client
  - docker build -t kalin-the-builder/multi-nginx ./nginx
  - docker build -t kalin-the-builder/multi-server ./server
  - docker build -t kalin-the-builder/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kalin-the-builder/multi-client
  - docker push kalin-the-builder/multi-nginx
  - docker push kalin-the-builder/multi-server
  - docker push kalin-the-builder/multi-worker