sudo:  required

services:
  - docker

before_install:
  - docker build -t kalinthebuilder/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kalinthebuilder/react-test npm test

afterafter_success:
  - docker build -t kalinthebuilder/multi-client ./client
  - docker build -t kalinthebuilder/multi-nginx ./nginx
  - docker build -t kalinthebuilder/multi-server ./server
  - docker build -t kalinthebuilder/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kalinthebuilder/multi-client
  - docker push kalinthebuilder/multi-nginx
  - docker push kalinthebuilder/multi-server
  - docker push kalinthebuilder/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "af-south-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-af-south-1-524382694030"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"